language: python
env:
  global:
    - RANDOM_SEED=0
    - secure: NUvkA8oTYsafUzz9HSRx1pMzWqYhPwo0rXsXdG475M282zLu1JUHgt82SKHQ6XsvJHCuuYvTIuE07PTzOt8zchu6bk4HUe0I/yS0m9FWm52ZAnJQDIfqXnzYjCpBgc8sNT33GqHsQfKBAQfRox5cJ06vbo1EDq/8KbH7R6DqOFfy9gzEHjjT3GGa/ABx1UmVczo5QhdUfVYfSM+ZfASITfFJvZbmog9MY7GKe44xmx7HYCc1KgURAzNg2P52VGZanb3qxLVaRy+IPgYLtkYjtzO5471NdvbhWJdKQXZqZX2lzzJqnQwLmFPKTxfL3oZKt7K5DO72vvXJVXy20osSkiGI16GmsxE5QX3KZ5xerungwHFb2kGnyHtox8SKEubK4eAfVgQ+/HrnYt1E1btBTwZWzQY+EuEE3xwMxpKj+d9FwpH+s6DhjjEQdDmvw0EZiNlyfWlo+zGhYJJV9c9dcj6tEkBQshmIUiHRu0BE9LT4swinY1tPMQKJLULZ4mRrpZj8GTDmIBkq3sXWrmZYbbVzFsaCog9V9JMTR5hqPM9yOHZyENpCHUWGgM0PnIuVJA3WOE5r+lpIb2eABctfVxQIt8x9C183jrjPS37TvzHioDgyHPcsfFU6fefAQ4X1uml/C8xZpMSMjePQ+KzMPV2LzVf34WFpufpmJ7m5HMc=

python:
  - 3.6

cache:
  pip: true
  directories:
    - .venv

before_install:
  - pip install pipenv
  - make doctor

install:
  - make install

script:
  - make check
  - make test

after_success:
  - pip install coveralls scrutinizer-ocular
  - coveralls
  - ocular
  - git config --global user.name "semantic-release (via TravisCI)"
  - git config --global user.email "semantic-release@travis"
  - pip install python-semantic-release
  - semantic-release publish

notifications:
  email:
    on_success: never
    on_failure: never
