language: python
env:
  global:
    secure: aK9xBVr2cjaYeLuYhZRXDRYfXzOTxcHTiDwq/eQre4HmnvDkRzrOl6Ele/hwmgGcHrfsDlAJrENIVAN5pwv/JVldTnVz0Vco41FFEDzhIzfN3J/6cxNfkdlp7r52uJW2GHru2863b538r13U8Rj1OJJbIvdECEM8zBgSqIJv+5IFS4qdrcVr3gRzhwOBrVUB5YoyCQUdNzhAWoRCHw4cX9yWaVM6ddwArLd64vKDU2O2Zgwa0AvS5BaMkfQX/AQVXyxV5pFDS9XlPzjO1JQxnEKOEawMl3oR2Xa3NiImckxqQFqR0TGV5zkr41dNPasQUTOMPpfdFfTeOfcMoVGEuFBYR+2KFsssgX/vlCW9w2G61mxTcABwglvreE09kfTFyM25Ep7/YQ/McDt6X7g9+4odNlXHFhZHXDbEGukfdvp0zlbix2uTRqGlOS0IE0tNxiaZeZQmDYh2+Ry9wyeBZSM739SocQzb2vQPUaB5e2MJN54U+aB5ZYVqYJuXg9lZYEDFBIU7C0xPZJjck+4spxXVFrOGDEsvTeewQXA/r62NjVoYAV5A2kTjmQzdsKWRoEZc4p+6ilIlZPaXtP59EBISLnsiFhwf1hnMkrFu1FwO1Nqmb7KrYDYj/O9lbJiYg9yMdMNGNZtXADgl5nZnTDj8cpt0+j4uGs77bWB7Jxo=
notifications:
  email: false
python:
  - '3.4'
env:
 - TOX_ENV=isort
 - TOX_ENV=flake8
 - TOX_ENV=py3-tests
 - TOX_ENV=coverage
before_install:
  - pip install tox coverage flake8 pytest isort coveralls
script:
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py
  - tox -e $TOX_ENV
after_success:
  - python travis_after_all.py https://api.travis-ci.com
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          coveralls
        fi
      fi
  # - coveralls
  # - git config --global user.name "semantic-release (via TravisCI)"
  # - git config --global user.email "ken.mercus.lai@gmail.com"
  # - pip install git+https://github.com/KenMercusLai/python-semantic-release.git
  # - semantic-release publish
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
