language: python
notifications:
  email: false
python:
    - "3.4"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install python-semantic-release
script:
    - py.test --cov .
after_success:
    coveralls
